### ISSUE TITLE
"Mimikyu" results in 404 from endpoint

### ISSUE THREAD

**Issue by CodemanBirdy** [PokeAPI/pokedex#170]
The endpoint `pokemon/mimikyu` is returning a 404 from the API. Using the Pokedex ID returns `mimikyu-disguised` which adds some confusion when dealing with pokemon name inputs but it's minor and can be worked around.

**Comment by shockthetoast** [comment]
You want the "pokemon-species" endpoints, not the "pokemon" endpoint:
https://pokeapi.co/api/v2/pokemon-species/mimikyu

The "pokemon" endpoint has a different listing for each major variant of a Pokémon - any time the difference is more than visual. The first form entry for each pokemon will use the dex ID, which is why that gave you mimikyu-disguised.

The data from the pokemon-species endpoint can get you to the various forms/variants.
