### ISSUE TITLE
How pokemon ids are determined..

### ISSUE THREAD

**Issue by SQWiperYT** [PokeAPI/pokedex#9]
I kinda working on pokemon galarian forms But I am confused about ids. Can someone clarify me, where I can found them

**Comment by Naramsim** [comment]
Hi @SQWiperYT, pokemon are divided in `pokemon`, `species` and `forms`. The `species` groups several pokemon under one category, for example, the species _deoxys_ [includes](https://pokeapi.co/api/v2/pokemon-species/386/) 4 varieties, these varieties are pokemon. 

Sometimes, due to our data format, is not possible to have a single pokemon with many forms. We have to add new pokemon with a similar name to our pokemon list. That's what happened with Deoxys, in fact, there is one Deoxys with his real ID (386), and four other with IDs greater than 10000.

Currently, in our database we don't have the Pokedexes for Galar yet, but you can assume that every pokemon of gen-8 is in Galar. So by querying https://pokeapi.co/api/v2/generation/8/ you get a list of all the Galar pokemon with their ID as part of the URL.

**Comment by Naramsim** [comment]
Hi @SQWiperYT, are you still on this issue?
